# Global configuration
spring:
  application:
    name: Bank System API
  profiles:
    active: @spring.profiles.active@

  datasource:
    #url: jdbc:postgresql://52.71.69.66:5432/ddn0otd9vhpaof
    platform: postgresql
    url: jdbc:postgresql://ec2-52-71-69-66.compute-1.amazonaws.com:5432/ddn0otd9vhpaof
    username: lvsftbbwjjwmde
    password: 653711af55eaddfa0862f617c976a4db5a3692b3329849a50e50f3569f762414
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

#Tomcat configuration
server:
  port: ${PORT:9900}
  servlet:
    context-path: /bank-system

#Log level configuration
logging:
    level:
      root: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            h2: INFO
          web:
            embedded:
              tomcat: INFO

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
