spring:
  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: 'sa'
    password: ''

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
