spring:
  profiles:
    active: '@spring.profiles.active@'
  main:
    banner-mode: off

logging:
  level:
    root: OFF

#bank:
#  url: http://localhost:9900/bank-system/api/v1/

bank:
  url: http://odg18-bank.herokuapp.com/bank-system/api/v1/